language: java
sudo: false

script: 
  - cd "Functional programming"
  - mvn clean test
  
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
  
after_failure:
  - echo "Build was failed"